# Generated by Django 5.0.6 on 2024-05-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('qualifications', models.TextField()),
                ('close_date', models.DateField()),
            ],
            options={
                'db_table': 'job_post',
            },
        ),
    ]
