# Generated by Django 5.0.6 on 2024-05-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Published', 'Published'), ('Closed', 'Closed')], default='Pending', max_length=20),
        ),
    ]
