# Generated by Django 5.0.6 on 2024-05-17 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_leaverequest_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='leaverequest',
            table='LeaveRequest',
        ),
    ]
